export ZSH="$HOME/.oh-my-zsh"
source /usr/share/zsh-antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# oh-my-zsh plugins
antigen bundle webyneter/docker-aliases.git
antigen bundle unixorn/docker-helpers.zshplugin
antigen bundle DarrinTisdale/zsh-aliases-exa.git
antigen bundle zdharma/fast-syntax-highlighting
antigen bundle git
antigen bundle gko/ssh-connect
antigen bundle pbar1/zsh-terraform
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle history-substring-search

# Non oh-my-zsh plugins
# antigen bundle zsh-users/zsh-syntax-highlighting

# Platform dependant bundles
if [[ 'uname' == 'Linux' ]]
then
    antigen bundle command-not-found
elif [[ 'uname' == 'Darwin' ]]
then
    antigen bundle brew
    antigen bundle iterm2
    antigen bundle osx
fi

# Theme
antigen theme romkatv/powerlevel10k

POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user dir_writable dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time root_indicator background_jobs time disk_usage ram)
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
#POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
#POWERLEVEL9K_USER_ICON="\uF415" # 
POWERLEVEL9K_ROOT_ICON="\uF09C"
#POWERLEVEL9K_SUDO_ICON=$'\uF09C' # 
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
#POWERLEVEL9K_VCS_GIT_ICON='\uF408 '
#POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uF408 '

ZSH_DISABLE_COMPFIX=true

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

antigen apply

if [ -f ~/.bash_profile ]; then
    . ~/.bash_profile;
fi
