#!/usr/bin/env zsh

# Add extra folders to PATH
export PATH=$PATH:$HOME/.local/bin

# Oh My Zsh
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.dotfiles/zsh
export HIST_STAMPS="yyyy-mm-dd"

POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user dir_writable dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time root_indicator background_jobs time disk_usage ram)
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_USER_ICON="\uF415" # 
POWERLEVEL9K_ROOT_ICON="\uF09C"
POWERLEVEL9K_SUDO_ICON=$'\uF09C' # 
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_VCS_GIT_ICON='\uF408 '
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uF408 '

ZSH_DISABLE_COMPFIX=true

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

# Default plugins to enable
plugins=(general wd)
typeset -aU plugins

# Read extra plugins from files
if [ -f "$HOME/.plugins" ]
then
  plugins+=($(<"$HOME/.plugins"))
fi

export ZSH_THEME="powerlevel10k/powerlevel10k"

source "$ZSH/oh-my-zsh.sh"

# Base16 Shell
export BASE16_SHELL=$HOME/.config/base16-shell/
if [ -n "$PS1" ] && [ -s "$BASE16_SHELL/profile_helper.sh" ]
then
  eval "$("$BASE16_SHELL/profile_helper.sh")"
fi

# Source any extra aliases
if [ -f "$HOME/.aliases" ]
then
  source "$HOME/.aliases"
fi

# Set default editor to Vim
export EDITOR='vim'
